### ISSUE TITLE
Incorrect argument name in /modules/net-vpc/main.tf for resource "google_compute_route" "ilb"

### ISSUE THREAD

**Issue by chinmaydorlikar** [terraform-google-modules/cloud-foundation-fabric#119]
The argument name "next_hop_ilb" is causing an issue while creating a shared vpc for a project.
Although the resource shouldn't be ideally called while making a shared VPC without custom routes, terraform plan blurts out an error.

![Screenshot (66)](https://user-images.githubusercontent.com/37778372/88844168-e5c54d80-d1ff-11ea-993a-1e054cec628d.png)

**Comment by ludoo** [comment]
That's pretty strange as it's one of our most used modules. Could you share the variables you're passing in to the module, and provider version you're using?

**Comment by chinmaydorlikar** [comment]
Provider details:
google : version     = "~>2.0"
google-beta : latest
Variables as passed:
project_id =XXXXXX
name = XXX
subnets[ { ip_cidr_range, name, region, secondary_ip_range{ pods, services}}]
shared_vpc_host = true
shared_vpc_service_projects = [XXXXX]
iam_roles = {region/subnet_name = []}
subnet_private_access = {region/subnet_name = true]}
subnet_flow_logs = {region/subnet_name = true]}

**Comment by ludoo** [comment]
I just tested this, and you need version 3.x of the google provider.
