### ISSUE TITLE
Extend the gke-cluster module to support shared VPC configuration

### ISSUE THREAD

**Issue by robertojrojas** [terraform-google-modules/cloud-foundation-fabric#123]
Currently, the [gke-cluster](../modules/gke-cluster) module does not appear to allow specifying a host project ID and shared VPC network.
```
 module "gke-dev-cluster" {
  source                    = "github.com/terraform-google-modules/cloud-foundation-fabric/modules/gke-cluster"
  name                      = "gke-dev-cluster"
  project_id                = "gke-dev-3291"
  location                  = local.location
  network                   = local.network
  subnetwork                = local.gke_subnetwork
  secondary_range_pods      = "pods"
  secondary_range_services  = "services"
  default_max_pods_per_node = 32

  peering_config = {
     import_routes = true
     export_routes = false
  }
  
  ....

}

```
As you can see in the configuration above, when using the **peering_config**, one can only specify a single **project_id** and **network**, which in turn is used by both the GKE cluster and **google_compute_network_peering_routes_config** as per this code:

**[modules/gke-cluster/main.tf](../modules/gke-cluster/main.tf)**

```
resource "google_container_cluster" "cluster" {
  ...
  project                     = var.project_id
   ...
  network                     = var.network
  ...
}
....
resource "google_compute_network_peering_routes_config" "gke_master" {
  ...
  project              = var.project_id
  ...
  network              = element(reverse(split("/", var.network)), 0)
  ...
}
```
In a Shared VPC scenario where the network is shared by host project, one would need to specify host project id and the shared vpc so the peering is setup on that host project.

To make this possible, the following proposes adding configuration block (**peering_config_shared_vpc**) like the following, which will allow specifying a host project id and a shared vpc:

```
module "gke-dev-cluster" {
  source                    = "github.com/terraform-google-modules/cloud-foundation-fabric/modules/gke-cluster"
  name                      = "gke-dev-cluster"
  project_id                = "gke-dev-3291"
  location                  = local.location
  network                   = local.network
  subnetwork                = local.gke_subnetwork
  secondary_range_pods      = "pods"
  secondary_range_services  = "services"
  default_max_pods_per_node = 32

  peering_config = {
     import_routes = true
     export_routes = false
  }

  peering_config_shared_vpc = {
     network    = "gke-dev-shared-vpc"
     project_id = "gke-dev-shared"
  }
  ...
}
```
I'm planning to submit a PR with the proposed solution. Of course, all open to discussion and changes. :)

**Comment by ludoo** [comment]
Hey, thanks for the report and PR! One question: why would you need to specify a separate network from the one the cluster gets created in?

**Comment by robertojrojas** [comment]
Hey, You're welcome! 
That's a good question. We could probably get away with just specifying the `host project id`. I didn't try that scenario. I'll give it a try real quick to see if that works. 
I'll keep you posted.

**Comment by robertojrojas** [comment]
@ludoo Your questions was accurate and yes one only needs to supply the `host project id` to configure the peering for a Shared VPC. I went through some tests and it worked well.
Instead of using a block like example above, a single input variable (**peering_config_project_id**) would suffice:
```
module "gke-dev-cluster" {
  source                    = "github.com/terraform-google-modules/cloud-foundation-fabric/modules/gke-cluster"
  name                      = "gke-dev-cluster"
  project_id                = "gke-dev-3291"
  location                  = local.location
  network                   = local.network
  subnetwork                = local.gke_subnetwork
  secondary_range_pods      = "pods"
  secondary_range_services  = "services"
  default_max_pods_per_node = 32

  peering_config = {
     import_routes = true
     export_routes = false
  }

  peering_config_project_id = "gke-dev-shared"

  ...
}
```
If this makes sense to you, I'll go ahead and update the PR #124

**Comment by ludoo** [comment]
Great, and thanks for checking!

The project id could also be derived from the network self link, but it would be more fragile so I much prefer your choice of passing it in via variables. Would it make sense to you to use `peering_config` instead of adding a new variable, further cluttering the already complex namespace of this module?

Something like

```hcl
variable "peering_config" {
  description = "Configure peering with the master VPC for private clusters."
  type = object({
    export_routes = bool
    import_routes = bool
    project_id = string
  })
  default = null
}
```

And in actual use, one can simply set the project id to `null` to use the default one. Would that work for you?

**Comment by robertojrojas** [comment]
I thought about doing it like that, but it would mean the `project_id` would be come a required variable just like the bool variables already there. I couldn't find a way to include the `project_id` inside the block and at the same time make it optional. I felt like having a separate variable being optional was a bit easier on the user so they won't have to specify it unless they need to.

**Comment by robertojrojas** [comment]
In any event, I'm open to either approach. :)

**Comment by ludoo** [comment]
The `gke-cluster` module already has ~20 variables, I'm a bit way about adding more. Putting it in `peering_config` will make it required, but only when `peering_config` is set. In my opinion the tradeoff is acceptable, while having two top-level peering-related variables will be more confusing.

If it's even remotely acceptable for you, that would be my preferred approach. :)

**Comment by robertojrojas** [comment]
Fair enough! I'll make the changes to the PR soon.
