### ISSUE TITLE
Invalid for_each argument when using folder_unit

### ISSUE THREAD

**Issue by tvvignesh** [terraform-google-modules/cloud-foundation-fabric#148]
Hi. I am trying to use the folder_unit module within foundation and I get this error:

<img width="593" alt="1" src="https://user-images.githubusercontent.com/1165845/94678811-b7b5d400-033c-11eb-8101-9a843077423f.png">

<img width="634" alt="2" src="https://user-images.githubusercontent.com/1165845/94678819-bbe1f180-033c-11eb-8c30-505c38950cde.PNG">

Not sure, but I guess the service account email is determined at runtime. Also did refer this: https://discuss.hashicorp.com/t/for-each-value-depends-on-resource-attributes-that-cannot-be-determined-until-apply/6061

May I know how I can solve this? 

Running TF 0.13.2

**CC:** @ludoo

**Comment by ludoo** [comment]
That module is kind of fragile and very sensitive to input arguments. Can you share how you're calling it?

**Comment by tvvignesh** [comment]
@ludoo Sure. This is how:

```hcl
module "mymodule" {
  source                = "../modules/folders-unit"
  name                  = "My Unit"
  short_name            = "my-unit"
  automation_project_id = module.tf_project.project_id
  billing_account_id    = var.billing_account_id
  environments          = var.environments
  gcs_defaults          = var.gcs_defaults
  organization_id       = var.organization_id
  root_node             = module.root_folders.folders[1].id
}
```

Currently working around this by commenting out iam_service_account_bindings within the module.

**Comment by ludoo** [comment]
Yep, the problem is with `root_node = module.root_folders.folders[1].id` and is kind of unavoidable in its current state.

The module was not designed for scenarios where the parent is dynamic, as we usually split different resource management layers into different Terraform setups, each one using folder, bucket and service account created by the previous stage, for security reasons (I've been meaning to publish an article on this, but never find the time).

**Comment by ludoo** [comment]
We should probably note this fact in the module's README.

**Comment by tvvignesh** [comment]
@ludoo Sure. Things are working after commenting out the bindings. Adding bindings manually wherever I need it. So, I guess I can work with this now.
