### ISSUE TITLE
cloud-config-container modules not working

### ISSUE THREAD

**Issue by juliocc** [terraform-google-modules/cloud-foundation-fabric#152]
Looks like COS VMs launched using cloud-config-container cloud init are no longer working. Didn't dig too much into it but looks like there are some changes to COS that breaks it.

**Comment by ludoo** [comment]
This must be knew as I launched a few last week. Which ones do you try
exactly? If using f1 micro, keep in mind they are super slow to come up.

**Comment by juliocc** [comment]
I think e2-small. Did you use COS or ubuntu?

**Comment by ludoo** [comment]
Cos, from the ilb example
