### ISSUE TITLE
 An argument named "mtu" is not expected here.

### ISSUE THREAD

**Issue by prowerse** [terraform-google-modules/cloud-foundation-fabric#185]
Hello Team,
Thanks for fabulous minimal modules. I'm trying to create a minimal VPC with following script:

```
module "gke_vpc" {
  source     = "github.com/terraform-google-modules/cloud-foundation-fabric/modules/net-vpc"
  project_id = var.project_id
  name       = "gke-vpc"
  subnets = [
    {
      ip_cidr_range       = "10.0.0.0/24"
      name                = "gke-sub"
      region              = var.region
      secondary_ip_range  = {
        pods     = "10.1.0.0/20"
        services = "10.2.0.0/24"
      }
    }
  ]
}
```
Getting following error:

```
# terraform plan -var-file=dev-env.tfvars
Error: Unsupported argument
  on .terraform/modules/gke_vpc/modules/net-vpc/main.tf line 91, in resource "google_compute_network" "network":
  91:   mtu                             = var.mtu
An argument named "mtu" is not expected here.
```

Checked .terraform modules directory. It has mtu variable declared variable.tf.
Any help what's wrong here?

**Comment by ludoo** [comment]
Hey! Thanks for the kind words on the modules. :)

The `mtu` attribute was [added in version 3.45.0 of the Google provider](https://github.com/hashicorp/terraform-provider-google/blob/master/CHANGELOG.md#3450-october-28-2020), we probably need to bump the minimum provider version in the module. Can you try changing it and seeing if it fixes your issue, which is faster than waiting for a PR/merge?

**Comment by prowerse** [comment]
Hi @ludoo 
Appreciate the quick response!

I was referring to old providers. Bumped up provider version to 3.45 to get it worked.

old
```
provider "google" {
  version = "~> 3.43.0"
}
provider "google-beta" {
  version = "~> 3.43.0"
}
```

New
```
provider "google" {
  version = "~> 3.45.0"
}
provider "google-beta" {
  version = "~> 3.45.0"
}
```

Able to get plan generated. Thanks for help!
You can close the issue. I'm not sure If I can close this.

**Comment by ludoo** [comment]
Thanks for confirming! I will keep this open so we remember to bump the module's version.
