### ISSUE TITLE
Clarify vpc output key formats

### ISSUE THREAD

**Issue by LucaPrete** [terraform-google-modules/cloud-foundation-fabric#219]
The [current vpc output documentation](https://github.com/terraform-google-modules/cloud-foundation-fabric/tree/master/modules/net-vpc#outputs) doesn't specify the format of the key to pull data out of the subnet_regions, subnet_secondary_ranges and subnet_self_links maps.
It would be good for users to know the exact key.

**Comment by ludoo** [comment]
Feel free to send a PR for the module's README Luca, there are examples in other modules, but still worth having in `net-vpc`. Good catch.
