### ISSUE TITLE
Adding short names for the GCS nomenclature instead of the complete region

### ISSUE THREAD

**Issue by chinmaydorlikar** [terraform-google-modules/cloud-foundation-fabric#227]
I have observed that in the case of regional buckets, the complete region is included in the name of the bucket 
(prefix-us-central1-suffix), this is due to the default logic that if the bucket is multi-regional then the regional prefix is simply us or eu which makes sense. But in the case of regional buckets, can we use short names of the regions?
This can certainly help:
`module "utils" {`
`  source  = "terraform-google-modules/utils/google"`
`  version = "~> 0.3"`
`  region  = "us-central1"`
`}`
Anything that's already stopping us from doing so?

**Comment by ludoo** [comment]
As per comments in the PR.
