### ISSUE TITLE
Error when changing or removing environment in environments list variable

### ISSUE THREAD

**Issue by kenn9j** [terraform-google-modules/cloud-foundation-fabric#23]
On using the Environment-based organizational sample, with 4 environments first, all went smoothly. 

When I changed environments list variable (see below - removed "nonprod"),

```
variable "environments" {
  description = "Environment short names."
  type        = list(string)
  default     = ["prod","nonprod","test","dev"]
  # default     = ["prod","nonprod","test","sandpit"]
} 
```
 I received this error.

```
Error: Error in function call

  on .terraform/modules/service-accounts-tf-environments/terraform-google-modules-terraform-google-service-accounts-2db8e39/outputs.tf line 44, in output "emails":
  44:   value       = zipmap(var.names, google_service_account.service_accounts[*].email)
    |----------------
    | google_service_account.service_accounts is tuple with 4 elements
    | var.names is list of string with 3 elements

Call to function "zipmap" failed: number of keys (3) does not match number of
values (4).
```

**Comment by ludoo** [comment]
Yup, it's a know issue with Terraform outputs, and we need to patch the service accounts module (and a few others using the same pattern) to account for that. The easy workaround is to comment all outputs before applying when you changhe `var.names`, and then uncomment them once you have successfully applied.

**Comment by ludoo** [comment]
I'm working on a [PR in the service-accounts module](https://github.com/terraform-google-modules/terraform-google-service-accounts/pull/14) that should fix this. Once it's stable I will port it to the other modules suffering from the same issue (eg cloud storage). Thanks for your patience.
