### ISSUE TITLE
CORS support for gcs module

### ISSUE THREAD

**Issue by chinmaydorlikar** [terraform-google-modules/cloud-foundation-fabric#231]
Any reason why we don't support a dynamic cors block in the GCS module?

**Comment by ludoo** [comment]
We probably never needed it before :) Care to send a PR? If you do just assign it to me and I'll speed it in.

**Comment by chinmaydorlikar** [comment]
Sure! I send one asap. I'll update the README as well. Thanks.

**Comment by ludoo** [comment]
Thanks *a lot* for the PR! If you need us to cut a release quickly just let us know!
