### ISSUE TITLE
Call to function "list" in ../../modules/gke-cluster/main.tf failed

### ISSUE THREAD

**Issue by kumar-dhanagopal** [terraform-google-modules/cloud-foundation-fabric#247]
I was trying out the example in `.../networking/hub-and-spoke-peering` using Terraform (v0.15.3) from within Cloud Shell.

The `plan` command returned the following error:

```
Error: Error in function call
│
│   on ../../modules/gke-cluster/main.tf line 105, in resource "google_container_cluster" "cluster":
│  105:     for_each = length(var.master_authorized_ranges) == 0 ? [] : list(var.master_authorized_ranges)
│     ├────────────────
│     │ var.master_authorized_ranges is map of string with 3 elements
│
│ Call to function "list" failed: the "list" function was deprecated in Terraform v0.12 and is no longer available; use tolist([ ... ]) syntax to write a literal list.
```
Going by the last line in the error message, it appears that the error occurred because I'm using a version that's higher than 0.12.  But, interestingly, the same example worked fine when I tested from an *off-cloud* host that has Terraform v0.14.11.

**Comment by ludoo** [comment]
We haven't yet verified and aligned code for terraform 0.15...

**Comment by rosmo** [comment]
@kumar-dhanagopal can you try replacing the list with tolist()?

**Comment by kumar-dhanagopal** [comment]
Yes, @rosmo . I was able to create an execution plan and apply it after changing `list()` to `tolist([...])`.

**Comment by ludoo** [comment]
Thanks Taneli for the quick fix!
