### ISSUE TITLE
Support for random project id?

### ISSUE THREAD

**Issue by jabcoder** [terraform-google-modules/cloud-foundation-fabric#266]
Under the foundations>environments without specifying a random suffix in the project name there is a chance that the project will not be created if it is not unique. Can we add the random_project_id variable or am I just missing something?

**Comment by ludoo** [comment]
We're usually very wary of adding random resources in the code, as they sometimes tend to behave in a counterintuive way.

You easily add your own random resource and use it as the `prefix` variable (or generate it outside and put it as prefix in your tfvars file). Would that work?
