### ISSUE TITLE
Can we have a project with the name different from the project_id ?

### ISSUE THREAD

**Issue by sly92** [terraform-google-modules/cloud-foundation-fabric#286]
I couldn't create a project with a name différent from the project_id. Is there a reason ?

i'd have for example : 

id: prj-c-logging-1c78
name: prj-c-logging

this module allow it:
https://github.com/terraform-google-modules/terraform-google-project-factory

**Comment by ludoo** [comment]
You're definitely welcome to use the project factory module if that better suits your needs. Feature parity is not one of our goals (in both ways, meaning we have feature pf does not have).

That said, adding a `name` variable with a `null` default, that preserves the current behaviour if no name is specified, is a trivial fix, would you care to send us a PR or do you prefer us doing it?

**Comment by sly92** [comment]
Of course, I'll

**Comment by sly92** [comment]
project_id          = "${local.prefix}${var.name}"
name                = "${local.prefix}${var.name}"

**Comment by sly92** [comment]
I did the change and tested it but I have a 403 when try to push my change to create pull request
