### ISSUE TITLE
project creation fails if skipDefaultNetworkCreation org policy is enforced

### ISSUE THREAD

**Issue by juliocc** [terraform-google-modules/cloud-foundation-fabric#31]
Might be related to terraform-providers/terraform-provider-google#3582

https://github.com/terraform-google-modules/cloud-foundation-fabric/blob/479be4d47d27440a2de6066acfbbc2300aa1a7cf/modules/project/main.tf#L42 #

**Comment by ludoo** [comment]
Yup, we need an extra variable in the project module. I'll send a PR shortly, unless you beat me to it. :)

**Comment by morgante** [comment]
@ludoo Why do we need an extra variable? To be clear, this is a provider bug and if we're still observing it let's make that clear on the provider bug.

"auto_create_network = false" should work regardless of whether the org policy exists or not.
