### ISSUE TITLE
example infrastructure/shared-vpc: failing to provision

### ISSUE THREAD

**Issue by bdelv** [terraform-google-modules/cloud-foundation-fabric#34]
I tried to launch without success the example infratructure/shared-vpc

First issue is 3 errors like this one:
```
Error: "enable_flow_logs": [REMOVED] This field is being removed in favor of log_config. If log_config is present, flow logs are enabled. Please remove this field

  on .terraform/modules/net-vpc-host/terraform-google-modules-terraform-google-network-e273b5e/main.tf line 51, in resource "google_compute_subnetwork" "subnetwork":
  51: resource "google_compute_subnetwork" "subnetwork" {
```
Passed by forcing the Google provider to pre-3.0
```
provider "google" {
  version = "~> 2.0"
}
provider "google-beta" {
  version = "~> 2.0"
}
```
Now bumping on the following error:
```
Error: Error setting billing account "xxxxxx-xxxxxx-xxxxxx" for project "projects/testvpc3-gce": googleapi: Error 400: Precondition check failed., failedPrecondition

  on .terraform/modules/project-service-gce/terraform-google-modules-terraform-google-project-factory-46e55ae/modules/fabric-project/main.tf line 30, in resource "google_project" "project":
  30: resource "google_project" "project" {
```
It's the same issue I couldn't solve for the tests of terraform-google-bootstrap.

Gave the "billing account user" role to the terraform service account, but didn't solve it.

Do you think I could have missed something or is it by "chance" a known issue? :)

**Comment by bdelv** [comment]
hum, I seem to be out of billing links quota on the test account I was using

By using the gcloud command directly to link the billing account to the project, I have a clearer error message than what TF was giving me:
```
ERROR: (gcloud.alpha.billing.accounts.projects.link) FAILED_PRECONDITION: Precondition check failed.
- '@type': type.googleapis.com/google.rpc.QuotaFailure
  violations:
  - description: 'Cloud billing quota exceeded: https://support.google.com/code/contact/billing_quota_increase'
```

Waiting for the quota upgrade to validate that it solved it.

**Comment by bdelv** [comment]
It works with the billing links quota upgrade.
Only remains the Google provider constraint issue.

**Comment by ludoo** [comment]
Thanks for the report, we need to update the sample to use the latest module versions, will do so as soon as I have 5 free minutes, hopefully today!
