### ISSUE TITLE
BigQuery dataset: support for role/... access format

### ISSUE THREAD

**Issue by Ziemowit-LH** [terraform-google-modules/cloud-foundation-fabric#356]
Thank you for the modules and the ease of management they provide.

Is there a good reason why roles available in "_access = {}_" are only limited to 'OWNER', 'READER', 'WRITER'?
We can grant other roles to datasets using direct "_google_bigquery_dataset_access_" resource block, like "_roles/bigquery.user_"?

Could the module handle both 'OWNER', 'READER', 'WRITER' and the "roles/..." format by internally converting "roles/bigquery.dataOwner", "roles/bigquery.dataViewer",  "roles/bigquery.dataEditor" to the legacy format and leaving others alone?

I think this is how "terraform-google-modules/bigquery/google" handles this.

Hmmm, may need to ~~merge~~concat members of _LEGACY_ and _roles/..._ for those 3, depending on how it's handled in the module.

**Comment by ludoo** [comment]
The second example in the module's README shows how to control access via IAM roles, which seems to be what you want:

```
module "bigquery-dataset" {
  source     = "./modules/bigquery-dataset"
  project_id = "my-project"
  id          = "my-dataset"
  iam = {
    "roles/bigquery.dataOwner" = ["user:user1@example.org"]
  }
}
```

Feel free to reopen if you feel this is not the case.

**Comment by Ziemowit-LH** [comment]
@ludoo
The readme says that _iam_ block is mutually exclusive with _access_.
We need to authorize views - that is only possible with the _access_ block, so we have to use it.

**Comment by ludoo** [comment]
Ah, good point. I don't remember why we put that in the READMe, but I don't see anything in our module preventing you from using both. What I imagine is we adopted the warning that you see in the [google_bigquery_dataset_access resource documentation](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/bigquery_dataset_access) about permadiffs. If you use it and it breaks, let us know and we'll try to deep dive on why.

**Comment by Ziemowit-LH** [comment]
@ludoo 
I can confirm that using _iam_ block destroys authorized views.
In fact, this is regardless of whether we use the fabric modules or not - this is the GCP itself.
Now I recall a situation where all the authorized views granted by hand to a dataset were destroyed with Terraform's single native resource _google_bigquery_dataset_iam_member_ definition.

**Comment by ludoo** [comment]
Is there anything we could do differently, in your view?

**Comment by juliocc** [comment]
I think if we remove [this condition](https://github.com/terraform-google-modules/cloud-foundation-fabric/blob/master/modules/bigquery-dataset/variables.tf#L24), the `access` attribute can be used with other roles. I'll give it a shot

**Comment by Ziemowit-LH** [comment]
There is potential for infinite diffs with just removing the condition - I mentioned it in the first post - and the solution may be to translate _role/_ format to the legacy name for these 3 special roles.
And also concat the _role/_ and legacy name members, if anybody happens to use both in specifying permissions in module call.

**Comment by juliocc** [comment]
@Ziemowit-LH can you try #359 and confirm it works for your use case?

**Comment by Ziemowit-LH** [comment]
@ludoo @juliocc 
Thank you for the addition.
This works fine with "dataset_access = false" - I'm going to use it like this!

This can't be used with "dataset_access = true", however, due to infinite diffs when, say, 'role = "roles/bigquery.dataViewer"' instead of 'role = "READER"'.

**Comment by juliocc** [comment]
You can rewrite roles/bigquery.dataViewer to READER before passing it to the module.

**Comment by Ziemowit-LH** [comment]
I guess you are right.
I can always do it on my side.

Thank you very much for your help.
