### ISSUE TITLE
Fix incoming links in medium articles (ludoo)

### ISSUE THREAD

**Issue by juliocc** [terraform-google-modules/cloud-foundation-fabric#421]
### TL;DR

We recently change Fabric's repo structure. Please update your medium article links to point to the right location.

### Terraform Configuration

```hcl
NA
```

### Terraform Version

```sh
NA
```

### Additional information

Affected articles:
- [Fine-grained Cloud DNS IAM via Service Directory](https://medium.com/google-cloud/fine-grained-cloud-dns-iam-via-service-directory-446058b4362e)
- [Using Cloud Asset Inventory feeds for dynamic configuration and policy enforcement](https://medium.com/google-cloud/fine-grained-cloud-dns-iam-via-service-directory-446058b4362e)

**Comment by ludoo** [comment]
done
