### ISSUE TITLE
Fix incoming links in medium article (LucaPrete)

### ISSUE THREAD

**Issue by juliocc** [terraform-google-modules/cloud-foundation-fabric#425]
### TL;DR

We recently change Fabric's repo structure. Please update your medium article links to point to the right location.

### Terraform Configuration

```hcl
NA
```

### Terraform Version

```sh
NA
```

### Additional information

Affected articles:
- [Accessing GKE private clusters through IAP](https://medium.com/google-cloud/accessing-gke-private-clusters-through-iap-14fedad694f8)

**Comment by LucaPrete** [comment]
Fixed. Thanks @juliocc
