### ISSUE TITLE
I'm interested in this also ... bootstrapping a new GCP account coming from AWS with a fairly complex org. The examples in [https://github.com/terraform-google-modules/cloud-foundation-fabric] are great for organisational structure but they bootstrap terraform without using this module. This module seems preferable for getting a clean start to an account and observing good practices with regard to iam roles and groups etc.

### ISSUE THREAD

**Issue by gilesw-vion** [terraform-google-modules/cloud-foundation-fabric#45]
I'm interested in this also ... bootstrapping a new GCP account coming from AWS with a fairly complex org. The examples in [https://github.com/terraform-google-modules/cloud-foundation-fabric] are great for organisational structure but they bootstrap terraform without using this module. This module seems preferable for getting a clean start to an account and observing good practices with regard to iam roles and groups etc.
I'm particularly looking at business unit example in the fabric repo.

_Originally posted by @gilesw-vion in https://github.com/terraform-google-modules/terraform-google-bootstrap/issues/11#issuecomment-594140902_

**Comment by ludoo** [comment]
I'm not understanding if there's an ask here. You're free to use our examples, or the bootstrap module. Are you saying we should change our approach and integrate that module? Could you list in detail why do you think that's the case?
