### ISSUE TITLE
Disabling snat using Terraform - GKE

### ISSUE THREAD

**Issue by tvvignesh** [terraform-google-modules/cloud-foundation-fabric#88]
Hi. I faced an issue with the gke-cluster module in this repo relating to disabling SNAT. Have posted the complete details of the issue here: https://github.com/terraform-providers/terraform-provider-google/issues/6537

Any help? Not sure how to fix the problem. Thanks.

**Comment by ludoo** [comment]
Thanks for the report, I'm not sure that is possible with the current cluster resource. @drebes do you know better?

**Comment by tvvignesh** [comment]
@ludoo Thanks for your quick reply. Any other alternative which might work. Is it the gke-cluster module which is incompatible or the terraform gke resource itself? Thanks.

**Comment by ludoo** [comment]
@tvvignesh I don't see a way of disabling SNAT in the Terraform gke cluster resource.

**Comment by ludoo** [comment]
I'm going to close this since the feature needs to be present in the underlying resource.
